imports:
    - php

filter:
    excluded_paths: [vendor/*, tools/*, backup/*, tests/*, src/_data/skarp/*]

build:
    image: default-bionic
		dependencies:
			- libfann

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.22
                    pecl_extensions:
                        - fann
        analysis:
            dependencies:
                before:
                    - sudo apt-get install -y fann
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -   command: "composer phpunit"
                coverage:
                    file: "docs/coverage.xml"
                    format: "clover"
