imports:
    - php

filter:
    excluded_paths: [vendor/*, tools/*, backup/*, tests/*, src/_data/skarp/*]

build:
    image: default-bionic
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.22
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -   command: "composer phpunit"
                coverage:
                    file: "docs/coverage.xml"
                    format: "clover"
